[package]
name = "pre_tfhe_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.7.0", features = [ "boolean", "shortint", "integer", "x86_64-unix" ] }
rand = "0.8.5"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
recrypt = "0.13.1"
pad = "0.1.6"